### ISSUE TITLE
Crash When NEI 1.12-2.4.0.231 Is Used

### ISSUE THREAD

**Issue by Junrall** [CD4017BE/CD4017BE_lib#12]
[23:47:36] [Server thread/FATAL] [FML]: The following problems were captured during this phase
[23:47:36] [Server thread/ERROR] [FML]: Caught exception from nei (java.lang.ArrayIndexOutOfBoundsException: 32767)
[23:47:36] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at cd4017be.indlog.item.ItemTank.initCapabilities(ItemTank.java:53) ~[ItemTank.class:?]
	at net.minecraft.item.ItemStack.forgeInit(ItemStack.java:1215) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:112) ~[aip.class:?]
	at net.minecraft.item.ItemStack.<init>(ItemStack.java:98) ~[aip.class:?]
	at codechicken.lib.inventory.InventoryUtils.newItemStack(InventoryUtils.java:52) ~[InventoryUtils.class:?]
	at codechicken.nei.util.ItemStackMap.wildcard(ItemStackMap.java:224) ~[ItemStackMap.class:?]
	at codechicken.nei.util.ItemStackSet.with(ItemStackSet.java:23) ~[ItemStackSet.class:?]
	at codechicken.nei.init.NEIInitialization.loadModSubsets(NEIInitialization.java:329) ~[NEIInitialization.class:?]
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:73) ~[NEIInitialization.class:?]
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54) ~[ProxyClient.class:?]
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62) ~[NotEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[modpack.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[modpack.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:727) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[minecraft.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]
[23:47:37] [Server thread/DEBUG] [FML]: Reverting to frozen data state.

**Comment by CD4017BE** [comment]
CD4017BE/InductiveLogistics#3
