### ISSUE TITLE
Client crash when removing covers from Inductive Logistics pipes (SevTech)

### ISSUE THREAD

**Issue by coldino** [CD4017BE/CD4017BE_lib#18]
Client crashes *occasionally* when trying to remove a Factory Block (from Chisel) cover from Inductive Logistics pipes, but only while holding a pickaxe in your hand. 

* Does not seem to happen with vanilla blocks as covers.
* Have not yet tested with other tools, but an empty hand does not seem to trigger the issue.
* Pack is SevTech Ages 3.1.2, which uses CD4017BE_lib 6.4.6, but I've tried upgrading to 6.4.8 with no change in behaviour.

```
java.lang.NullPointerException: Unexpected error
	at team.chisel.client.render.ModelChisel.canRenderInLayer(ModelChisel.java:159)
	at team.chisel.ctm.client.asm.CTMCoreMethods.canRenderInLayer(CTMCoreMethods.java:33)
	at net.minecraft.block.Block.canRenderInLayer(Block.java)
	at team.chisel.common.block.BlockCarvable.canRenderInLayer(BlockCarvable.java:166)
	at cd4017be.lib.render.model.BlockMimicModel$ProviderBlockMimic.getModelFor(BlockMimicModel.java:138)
	at cd4017be.lib.render.model.MultipartModel$IModelProvider.getQuads(MultipartModel.java:210)
	at cd4017be.lib.render.model.MultipartModel$BakedMultipart.func_188616_a(MultipartModel.java:157)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SimpleBakedModel.java:121)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SimpleBakedModel.java:97)
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:835)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:46)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175020_a(CCBlockRendererDispatcher.java:53)
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:1938)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1375)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CD4017BE** [comment]
The crash happens inside Chisel's code. However when I tried to look up the source code on their GitHub repo to investigate the problem, oddly I couldn't find any of the two classes listed in your stacktrace above (in none of their 1.12 branches). They might have been deleted/replaced in some recent update.

Have you tried updating Chisel?

**Comment by CD4017BE** [comment]
Never mind: I have a very good guess what caused the NullPointerException and probably fixed it.

**Comment by coldino** [comment]
Excellent news, thanks.

I was waiting to see if you were able to work on this before dumping another one on you... It is also from removing covers, but with Extra Planets' Eris Stone and happen with an empty hand. I'll include it here but will happily move it to a different bug if you prefer.

```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=basictypeeris, clazz=class com.mjr.extraplanets.blocks.planetAndMoonBlocks.BlockBasicEris$EnumBlockBasic, values=[SURFACE, SUB_SURFACE, STONE, ORE_IRON, ORE_TIN, ORE_COPPER, ORE_DARK_IRON, DARK_IRON_BLOCK, STONEBRICKS, DUNGEON_BRICK]} as it does not exist in ExtendedBlockState{block=indlog:warp_pipe, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at com.mjr.extraplanets.blocks.planetAndMoonBlocks.BlockBasicEris.func_176195_g(BlockBasicEris.java:90)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at cd4017be.lib.block.AdvancedBlock.func_176195_g(AdvancedBlock.java:621)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:251)
	at net.minecraft.block.Block.func_180647_a(Block.java:559)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:246)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2249)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CD4017BE** [comment]
Nice, that one has already been fixed in https://github.com/MJRLegends/ExtraPlanets/commit/bbb8d8d5e43037797b3d50062e54e8ddcc635f20
