### ISSUE TITLE
NullPointerException when Chunk unloads, shuts down server thread

### ISSUE THREAD

**Issue by Endalion** [CD4017BE/CD4017BE_lib#19]
In the potentially unloaded chunk, there is 1x 32bit cable, 1x redstone emitter and 1x sensor reader with 1x Item sensor linked to a hopper.
```
[08:59:33] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at cd4017be.lib.tileentity.BaseTileEntity.getBlockState(BaseTileEntity.java:48) ~[BaseTileEntity.class:?]
	at cd4017be.lib.tileentity.BaseTileEntity.getOrientation(BaseTileEntity.java:59) ~[BaseTileEntity.class:?]
	at cd4017be.circuits.tileEntity.BlockSensor.update(BlockSensor.java:43) ~[BlockSensor.class:?]
	at net.minecraft.world.World.redirect$tileEntityUpdate$zba000(World.java:4132) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1835) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more

**Comment by CD4017BE** [comment]
Apparently the TileEntity of the Sensor Reader block still got ticked after being unloaded, that is normally not possible (as in vanilla forge v14.23.5.2768 I'm coding on)!

Do you have any additional mods installed, potentially ones that might mess with world/game ticking or chunk loading/unloading (including debug or performance monitor tools)?
What forge version are you using?
How does the crashing setup look in detail? I can't replicate the issue on my installation.

**Comment by Endalion** [comment]
I didn't know that is even possible... wait, (see end)

Forge v14.23.5.2836
Possible mod suspects:
- **AdPother (Pollution of the realms)**
- Optifine (Render regions **on**, dynamic chunkloading **on**)
- VanillaFix
- RTG (Realistic Terrain gen)
- FTBLib+Util (Was not touched in the affected world)

Directly involved mods:
- Magneticraft

I may have a prime suspect for a mod that messes with ticking. AdPother's pollution makes plants grow faster, this definitely manifests in manually called ticks. In the affected chunk there is AdPother pollution so it is extremely likely this is the cause.

**Comment by Flanks255** [comment]
I'm also getting this when the chunk unloads, on:
CD4017BE_Lib: 6.4.14.1
Auto redstone: 6.1.6
Forge: 14.23.5.2847

https://pastebin.com/pCrJUWDV
