### ISSUE TITLE
Crash after death on single player

### ISSUE THREAD

**Issue by marcin212** [CD4017BE/CD4017BE_lib#20]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OTGCorePlugin (OTG-Core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/17/19 7:20 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at cd4017be.rs_ctr.tileentity.part.SignalModule.render(SignalModule.java:118)
	at cd4017be.api.rs_ctr.interact.InteractiveDeviceRenderer.renderTileEntityFast(InteractiveDeviceRenderer.java:52)
	at cd4017be.lib.render.HybridFastTESR.func_192841_a(HybridFastTESR.java:43)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cd4017be.rs_ctr.tileentity.part.SignalModule.render(SignalModule.java:118)
	at cd4017be.api.rs_ctr.interact.InteractiveDeviceRenderer.renderTileEntityFast(InteractiveDeviceRenderer.java:52)
	at cd4017be.lib.render.HybridFastTESR.func_192841_a(HybridFastTESR.java:43)

-- Block Entity Details --
Details:
	Name: rs_ctr:panel // cd4017be.rs_ctr.tileentity.Panel
	Block type: ID #1141 (tile.rs_ctr.panel // cd4017be.rs_ctr.block.BlockGate // rs_ctr:panel)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (104,4,-9), Chunk: (at 8,0,7 in 6,-1; contains blocks 96,0,-16 to 111,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1141 (tile.rs_ctr.panel // cd4017be.rs_ctr.block.BlockGate // rs_ctr:panel)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:156)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:131)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['marcin212'/115, l='MpServer', x=103.50, y=4.00, z=-14.50]]
	Chunk stats: MultiplayerChunkCache: 575, 575
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (100,4,-20), Chunk: (at 4,0,12 in 6,-2; contains blocks 96,0,-32 to 111,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 19525 game time, 7543 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 21 total; [EntitySheep['Sheep'/96, l='MpServer', x=107.75, y=4.00, z=-69.78], EntitySheep['Sheep'/97, l='MpServer', x=98.50, y=4.00, z=-66.50], EntitySheep['Sheep'/98, l='MpServer', x=98.50, y=4.00, z=-70.50], EntityPlayerSP['marcin212'/115, l='MpServer', x=94.40, y=3.00, z=-14.70], EntitySheep['Sheep'/99, l='MpServer', x=96.50, y=4.00, z=-71.50], EntityPig['Pig'/100, l='MpServer', x=106.53, y=4.00, z=-31.23], EntityPig['Pig'/101, l='MpServer', x=114.57, y=4.00, z=-51.79], EntityPlayerSP['marcin212'/115, l='MpServer', x=103.50, y=4.00, z=-14.50], EntityPig['Pig'/102, l='MpServer', x=138.23, y=4.00, z=-39.65], EntityPig['Pig'/103, l='MpServer', x=139.53, y=4.00, z=-43.09], EntityDonkey['Donkey'/105, l='MpServer', x=153.66, y=4.00, z=-90.90], EntityDonkey['Donkey'/106, l='MpServer', x=156.52, y=4.00, z=-88.87], EntityCow['Cow'/107, l='MpServer', x=159.38, y=4.00, z=-90.38], EntityCow['Cow'/80, l='MpServer', x=27.58, y=4.00, z=-79.83], EntityCow['Cow'/81, l='MpServer', x=30.69, y=4.00, z=-93.19], EntityCow['Cow'/82, l='MpServer', x=43.30, y=4.00, z=-91.16], EntitySheep['Sheep'/83, l='MpServer', x=39.40, y=4.00, z=-87.32], EntityChicken['Chicken'/84, l='MpServer', x=42.50, y=4.00, z=57.50], EntityChicken['Chicken'/85, l='MpServer', x=38.54, y=4.00, z=54.49], EntityChicken['Chicken'/86, l='MpServer', x=38.78, y=4.00, z=58.15], EntityPig['Pig'/87, l='MpServer', x=42.51, y=4.00, z=58.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 793940640 bytes (757 MB) / 2178940928 bytes (2078 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version           | Source                                     | Signature                                |
	|:------ |:----------------------- |:----------------- |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2            | minecraft.jar                              | None                                     |
	| LCHIJA | mcp                     | 9.42              | minecraft.jar                              | None                                     |
	| LCHIJA | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar              | None                                     |
	| LCHIJA | forge                   | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar              | None                                     |
	| LCHIJA | otgcore                 | 1.12.2 - v8.2     | minecraft.jar                              | None                                     |
	| LCHIJA | foamfixcore             | 7.7.4             | minecraft.jar                              | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-1.0.0.29 | CTM-MC1.12.2-1.0.0.29.jar                  | None                                     |
	| LCHIJA | appliedenergistics2     | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar       | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | jei                     | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                  | None                                     |
	| LCHIJA | quark                   | r1.6-177          | Quark-r1.6-177.jar                         | None                                     |
	| LCHIJA | autoreglib              | 1.3-32            | AutoRegLib-1.3-32.jar                      | None                                     |
	| LCHIJA | openterraingenerator    | v8.2              | OpenTerrainGenerator-1.12.2 - v8.2.jar     | None                                     |
	| LCHIJA | biomebundle             | 5.1               | Biome_Bundle-1.12.2-v6.1.jar               | None                                     |
	| LCHIJA | blockcraftery           | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar             | None                                     |
	| LCHIJA | buildinggadgets         | 2.7.4             | BuildingGadgets-2.7.4.jar                  | None                                     |
	| LCHIJA | cd4017be_lib            | 6.4.13            | CD4017BE_lib-1.12.2-6.4.13.jar             | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44.jar               | None                                     |
	| LCHIJA | valkyrielib             | 1.12.2-2.0.20.1   | valkyrielib-1.12.2-2.0.20.1.jar            | None                                     |
	| LCHIJA | environmentaltech       | 1.12.2-2.0.20.1   | environmentaltech-1.12.2-2.0.20.1.jar      | None                                     |
	| LCHIJA | fastleafdecay           | v14               | FastLeafDecay-v14.jar                      | None                                     |
	| LCHIJA | foamfix                 | 0.10.8-1.12.2     | foamfix-0.10.8-1.12.2.jar                  | None                                     |
	| LCHIJA | forgelin                | 1.8.4             | Forgelin-1.8.4.jar                         | None                                     |
	| LCHIJA | gravestone              | 1.10.3            | gravestone-1.10.3.jar                      | None                                     |
	| LCHIJA | mekanism                | 1.12.2-9.8.2.389  | Mekanism-1.12.2-9.8.2.389.jar              | None                                     |
	| LCHIJA | teslacorelib            | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar | None                                     |
	| LCHIJA | nuclearcraft            | 2.18k             | NuclearCraft-2.18k-1.12.2.jar              | None                                     |
	| LCHIJA | integrationforegoing    | 1.12.2-1.9        | IntegrationForegoing-1.12.2-1.9.jar        | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCHIJA | journeymap              | 1.12.2-5.5.5      | journeymap-1.12.2-5.5.5.jar                | None                                     |
	| LCHIJA | jee                     | 1.0.8             | JustEnoughEnergistics-1.12.2-1.0.8.jar     | None                                     |
	| LCHIJA | jeresources             | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar    | None                                     |
	| LCHIJA | mekanismgenerators      | 1.12.2-9.8.2.389  | MekanismGenerators-1.12.2-9.8.2.389.jar    | None                                     |
	| LCHIJA | mekanismtools           | 1.12.2-9.8.2.389  | MekanismTools-1.12.2-9.8.2.389.jar         | None                                     |
	| LCHIJA | minecoprocessors        | 1.12.2-5          | minecoprocessors-1.12.2-5.jar              | None                                     |
	| LCHIJA | moreoverlays            | 1.15.1            | moreoverlays-1.15.1-mc1.12.2.jar           | None                                     |
	| LCHIJA | oreexcavation           | 1.4.143           | OreExcavation-1.4.143.jar                  | None                                     |
	| LCHIJA | psi                     | r1.1-77           | Psi-r1.1-77.jar                            | None                                     |
	| LCHIJA | railcraft               | 12.0.0            | railcraft-12.0.0.jar                       | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | rangedpumps             | 0.5               | rangedpumps-0.5.jar                        | None                                     |
	| LCHIJA | rs_ctr                  | 0.2.0             | RedstoneControl-1.12.2-0.2.0.jar           | None                                     |
	| LCHIJA | rsgauges                | 1.1.9             | rsgauges-1.12.2-1.1.9.jar                  | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | theoneprobe             | 1.4.28            | theoneprobe-1.12-1.4.28.jar                | None                                     |
	| LCHIJA | topaddons               | 1.12.2-1.12.0     | topaddons-1.12.2-1.12.0.jar                | None                                     |
	| LCHIJA | universalmodifiers      | 1.12.2-1.0.16.1   | valkyrielib-1.12.2-2.0.20.1.jar            | None                                     |
	| LCHIJA | zettaindustries         | 1.3               | zettaindustries-1.3-1.12.2-161.jar         | None                                     |
	| LCHIJA | mysticallib             | 1.12.2-1.4.0      | mysticallib-1.12.2-1.4.0.jar               | None                                     |
	| LCHIJA | teslacorelib_registries | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar           | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.0.29.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.2.389.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	[Psi] Active spell: None
	AE2 Integration: IC2:OFF, RC:ON, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: forge-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor 
```

- cd4017be_lib      6.4.13  
- forge                 14.23.5.2847  
- RedstoneControl 0.2.0

**Comment by CD4017BE** [comment]
The only way I could see this crash possibly happen is if the client network thread was updating the TileEntity state and thous invalidating the control panel component at the same time as the render thread was trying to draw it.

**Comment by asiekierka** [comment]
That's absolutely possible. Generally, you are expected to manually synchronize your networking code in a way where reading and parsing the packet happens off-thread, but the apply process is supposed to happen on the main client thread (you can see how vanilla does it, for example).
